name: build-atlas-plugins
run-name: Build Atlas plugins by @${{github.actor}}

on: 
    push:
        branches:
            - develop

jobs:
    build:              
        runs-on: ubuntu-latest              
        steps:
            - name: Install Power Platform tools
              uses: microsoft/powerplatform-actions/actions-install@v1

            - name: Checkout
              uses: actions/checkout@v4

            - name: Pack solution
              uses: microsoft/powerplatform-actions/pack-solution@v1
              with:
                solution-file: solution.zip
                solution-folder: Plugins Atlas/Solution
                solution-type: Unmanaged
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: solution-to-import
                path: solution.zip

    deployment:
        runs-on: ubuntu-latest
        environment: KRISTI
        needs: build
        steps:
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: solution-to-import

          - name: Deploy solution
            uses: microsoft/powerplatform-actions/import-solution@v1
            with:
              environment-url: https://crm-ti.dynamics.krista.services
              user-name: ${{ secrets.USERNAME }}
              password-secret: ${{ secrets.PASSWORD }}
              solution-file: solution.zip
                

            